### ISSUE TITLE
Support object store file layout 

### ISSUE THREAD

**Issue by Omega359** [JanKaul/iceberg-rust#34]
I'm migrating a spark workload to datafusion and I'd like to use iceberg tables with the new implementation. One of the things we found helped a lot with the spark / iceberg implementation wrt S3 was the java iceberg's [object store layout](https://iceberg.apache.org/docs/latest/aws/#object-store-file-layout) feature. From what I can see this doesn't seem to be supported here - am I mistaken or is is something that could be included?

**Comment by JanKaul** [comment]
Hi, thanks for raising this issue. The crate currently doesn't support the object store layout, but it would be a really great addition and I would like to support it.

If I understand correctly the path should look something like this:

base_path + /data/ + hash + /partition=partition_value/ + filename

And S3 is supposed to then partition the files automatically.

I think I can integrate it pretty easily.

**Comment by Omega359** [comment]
Normally when using this one would dedicate a bucket to the table such that the path would be /hash/...

**Comment by JanKaul** [comment]
I don't know if I should start this discussion but I feel like there is a trade-off here in where you place the hash in the key name. Placing it more in the front will make S3 partition it more likely. However. you're also loosing a bit of structure in your bucket because table files are scattered across these prefixes.

I wonder if you already get the performance benefits if you place the hash after the table-location but before the partitions. This way you could keep the structure of your bucket.

In the [talk](https://youtu.be/rHeTn9pHNKo?si=FUhaQ_ncskm_SLCq&t=3107) they say that S3 should be pretty smart in optimizing the partitions.

But I guess there is also the point of conforming with the Java implementation.

**Comment by Omega359** [comment]
That is a tradeoff for sure. It's essentially a workaround for s3 limits when a bucket isn't accessed enough to have it optimally partitioned. Without the hash we've often seen so many 503 errors from S3 when hitting a table hard from multiple machines (like during a data load) which caused our app to perform very poorly because we had to implement exponential backoffs.

I would only suggest implementing this if it was an easy thing to do. I recall looking at the java code to see how they did it and it was pretty simple but I doubt that will translate to your crate here (I haven't the time to investigate).

**Comment by JanKaul** [comment]
It's really easy to implement.

I think I'll by default use the scheme:

base_path + /data/ + hash + /partition=partition_value/ + filename

If `write.object-storage.enabled` is true and `write.data.path` is set it uses this scheme: 

write_data_path/ + hash + /filepath

Like you suggested. I think the default one should already bring almost all of the benefits. But you can still opt for the second one.
